# Generated by Django 5.1.1 on 2024-09-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invtry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drugid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drug',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
