# Generated by Django 5.1.1 on 2024-09-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invtry', '0002_alter_drug_drugid_alter_drug_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drugid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
