# Generated by Django 5.1.1 on 2024-09-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
